// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieMauiAPI.Data;

#nullable disable

namespace MovieMauiAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("MovieMauiAPI.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AO")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actors")
                        .HasColumnType("TEXT");

                    b.Property<int>("Adventure")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Animation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Awards")
                        .HasColumnType("TEXT");

                    b.Property<int>("Biography")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Box_office")
                        .HasColumnType("TEXT");

                    b.Property<int>("Comedy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<int>("Crime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<int>("Documentary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Drama")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Family")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fantasy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<int>("History")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Horror")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<int>("M_PG")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metascore")
                        .HasColumnType("TEXT");

                    b.Property<int>("Music")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Musical")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mystery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NC_17")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NOT_RATED")
                        .HasColumnType("INTEGER");

                    b.Property<int>("N_A")
                        .HasColumnType("INTEGER");

                    b.Property<int>("News")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nineties")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PASSED")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PG_13")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Poster")
                        .HasColumnType("TEXT");

                    b.Property<int>("R")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rated_G")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reality_TV")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Released")
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .HasColumnType("TEXT");

                    b.Property<int>("Romance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Runtime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sci_Fi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Short")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sport")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TV_14")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TV_G")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TV_MA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TV_PG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Thriller")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Two_Thousand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int>("UNRATED")
                        .HasColumnType("INTEGER");

                    b.Property<int>("War")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Western")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Writer")
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("eighties")
                        .HasColumnType("INTEGER");

                    b.Property<string>("image_file")
                        .HasColumnType("TEXT");

                    b.Property<string>("imdbID")
                        .HasColumnType("TEXT");

                    b.Property<string>("imdbRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("imdbVotes")
                        .HasColumnType("TEXT");

                    b.Property<int>("twenty_tens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("movies");
                });
#pragma warning restore 612, 618
        }
    }
}
